### ISSUE TITLE
Can't get it to work with external measured data

### ISSUE THREAD

**Issue by ahmetcemturan** [RobTillaart/runningAngle#10]
Hi, 
I have problems getting any average with external angle data.    I have the AS5600 sensor that gives 12bit readings for the angle.

I have tried both your libraries, runningAngle and AverageAngle but failed to get it to calculate any average.   
I am pretty sure that it's my fault as I am quite new to this.  
My code:
[runningAngle222.zip](https://github.com/RobTillaart/runningAngle/files/8790767/runningAngle222.zip)

Would appreciate any help

**Comment by RobTillaart** [comment]
Thanks for the issue, 
I will dive into it next week as my agenda is quite full (150++ libs to maintain)
You can also post it on the Arduino forum as there are more people that might be able to help you,

**Comment by RobTillaart** [comment]
Just had a look at the code
- I cannot compile as I do not have a AMS_5600 device (in fact I don't know it)
- What board are you using?
- What is the error message you get when you compile?

**Comment by RobTillaart** [comment]
Stripped all angle math from your sketch as I think you just don't get data from the device

Does this stripped version generate data?
```cpp

#include <AS5600.h>

AMS_5600 ams5600;//ACT

void setup() 
{
  Serial.begin(115200);
  Wire.begin(12,2);
}

void loop()
{
  int a0 = (4095 - ams5600.getRawAngle())*0.0879;
  Serial.println(a0);
  delay(100);
}
```

if not, your problem is in the AMS_5600 code.

(please post part of the output)

**Comment by ahmetcemturan** [comment]
Hi,
thanks for the prompt response,
The Board is a NodeMCU
I can compile, that is not the problem.
I get good readings from the AS5600.  The AS5600 is a magnetic direction Sensor (very practical,  you should definitely look into it)
My main project is an Anemometer with a windvane.
The library for the AS5600: [https://github.com/Seeed-Studio/Seeed_Arduino_AS5600](url)
The AS5600 website: [https://ams.com/en/as5600](url)


Some output:
13:08:57.407 -> heading  -   281.00/   a0  -   281/   smoothed  -   281.00 
13:08:57.509 -> heading  -   281.00/   a0  -   281/   smoothed  -   281.00 
13:08:57.610 -> heading  -   281.00/   a0  -   281/   smoothed  -   281.00 
13:08:57.711 -> heading  -   289.00/   a0  -   289/   smoothed  -   289.00 
13:08:57.813 -> heading  -   300.00/   a0  -   300/   smoothed  -   300.00 
13:08:57.915 -> heading  -   312.00/   a0  -   312/   smoothed  -   312.00 
13:08:58.017 -> heading  -   328.00/   a0  -   328/   smoothed  -   328.00 
13:08:58.119 -> heading  -   353.00/   a0  -   353/   smoothed  -   353.00 
13:08:58.221 -> heading  -   8.00/   a0  -   8/   smoothed  -   8.00 
13:08:58.323 -> heading  -   20.00/   a0  -   20/   smoothed  -   20.00 
13:08:58.425 -> heading  -   25.00/   a0  -   25/   smoothed  -   25.00 
13:08:58.527 -> heading  -   29.00/   a0  -   29/   smoothed  -   29.00 
13:08:58.629 -> heading  -   32.00/   a0  -   32/   smoothed  -   32.00 
13:08:58.731 -> heading  -   33.00/   a0  -   33/   smoothed  -   33.00 
13:08:58.833 -> heading  -   29.00/   a0  -   29/   smoothed  -   29.00 
13:08:58.935 -> heading  -   7.00/   a0  -   7/   smoothed  -   7.00 
13:08:59.037 -> heading  -   352.00/   a0  -   352/   smoothed  -   352.00 
13:08:59.139 -> heading  -   344.00/   a0  -   344/   smoothed  -   344.00 
13:08:59.207 -> heading  -   332.00/   a0  -   332/   smoothed  -   332.00 
13:08:59.308 -> heading  -   326.00/   a0  -   326/   smoothed  -   326.00 
13:08:59.409 -> heading  -   319.00/   a0  -   319/   smoothed  -   319.00 
13:08:59.511 -> heading  -   313.00/   a0  -   313/   smoothed  -   313.00 
13:08:59.613 -> heading  -   307.00/   a0  -   307/   smoothed  -   307.00 
13:08:59.715 -> heading  -   300.00/   a0  -   300/   smoothed  -   300.00 
13:08:59.817 -> heading  -   293.00/   a0  -   293/   smoothed  -   293.00

**Comment by ahmetcemturan** [comment]
I can run this library without problems:
[https://gitlab.com/yesbotics/libs/arduino/average-value](url)

obviously it does not work if the averaged data passes 359-1  but other than that it works.  (If that helps maybe to find out the difference)

**Comment by RobTillaart** [comment]
please give this a try and post its output:
```cpp
#include <AS5600.h>//ACT
#include <Wire.h>

//#include <AverageAngle.h>
#include <runningAngle.h>

AMS_5600 ams5600;//ACT

//  GLOBAL VARIABLES EXIST OUTSIDE FUNCTIONS
runningAngle heading(runningAngle::DEGREES);//optional


void setup() 
{
  Serial.begin(115200);
  Wire.begin(12,2);

  // only need to configure this once.
  heading.setWeight(0.1);
}

void loop()
{
  // MEASUREMENTS & MATH
  int raw = ams5600.getRawAngle();
  int a0 = 4095 - raw;
  float windcounts = a0 *0.0879 ;
  float smoothed_heading = heading.add(windcounts);

  // OUTPUT
  Serial.print("heading: ");
  Serial.print(heading.getAverage(), 1);
  Serial.print("\traw: ");
  Serial.print(raw);
  Serial.print("\ta0: ");
  Serial.print(a0);
  Serial.print("\twindcounts: ");
  Serial.print(windcounts, 1);
  Serial.print("\tsmoothed: ");
  Serial.print(smoothed_heading, 1);
  Serial.println();

  delay(100);
}
```

**Comment by RobTillaart** [comment]
> I can run this library without problems: https://gitlab.com/yesbotics/libs/arduino/average-value

That is a simple average of N numbers, it does not take into account that angles are on an (infinite) circle.

**Comment by ahmetcemturan** [comment]
```
14:46:00.717 -> heading: 11.9	raw: 3961	a0: 134	windcounts: 11.8	smoothed: 11.9
14:46:00.818 -> heading: 11.9	raw: 3961	a0: 134	windcounts: 11.8	smoothed: 11.9
14:46:00.920 -> heading: 11.9	raw: 3960	a0: 135	windcounts: 11.9	smoothed: 11.9
14:46:01.022 -> heading: 11.9	raw: 3959	a0: 136	windcounts: 12.0	smoothed: 11.9
14:46:01.124 -> heading: 12.1	raw: 3934	a0: 161	windcounts: 14.2	smoothed: 12.1
14:46:01.226 -> heading: 12.9	raw: 3870	a0: 225	windcounts: 19.8	smoothed: 12.9
14:46:01.328 -> heading: 14.0	raw: 3815	a0: 280	windcounts: 24.6	smoothed: 14.0
14:46:01.430 -> heading: 15.5	raw: 3767	a0: 328	windcounts: 28.8	smoothed: 15.5
14:46:01.532 -> heading: 17.2	raw: 3725	a0: 370	windcounts: 32.5	smoothed: 17.2
14:46:01.633 -> heading: 19.2	raw: 3675	a0: 420	windcounts: 36.9	smoothed: 19.2
14:46:01.735 -> heading: 21.1	raw: 3657	a0: 438	windcounts: 38.5	smoothed: 21.1
14:46:01.837 -> heading: 22.9	raw: 3652	a0: 443	windcounts: 38.9	smoothed: 22.9
14:46:01.939 -> heading: 24.5	raw: 3654	a0: 441	windcounts: 38.8	smoothed: 24.5
14:46:02.041 -> heading: 25.9	raw: 3655	a0: 440	windcounts: 38.7	smoothed: 25.9
14:46:02.142 -> heading: 27.2	raw: 3657	a0: 438	windcounts: 38.5	smoothed: 27.2
14:46:02.244 -> heading: 28.3	raw: 3658	a0: 437	windcounts: 38.4	smoothed: 28.3
14:46:02.346 -> heading: 29.3	raw: 3658	a0: 437	windcounts: 38.4	smoothed: 29.3
14:46:02.448 -> heading: 30.2	raw: 3658	a0: 437	windcounts: 38.4	smoothed: 30.2
14:46:02.549 -> heading: 31.0	raw: 3658	a0: 437	windcounts: 38.4	smoothed: 31.0
14:46:02.651 -> heading: 31.8	raw: 3658	a0: 437	windcounts: 38.4	smoothed: 31.8
14:46:02.753 -> heading: 32.4	raw: 3658	a0: 437	windcounts: 38.4	smoothed: 32.4
14:46:02.855 -> heading: 33.0	raw: 3658	a0: 437	windcounts: 38.4	smoothed: 33.0
14:46:02.957 -> heading: 33.6	raw: 3658	a0: 437	windcounts: 38.4	smoothed: 33.6
14:46:03.059 -> heading: 34.1	raw: 3658	a0: 437	windcounts: 38.4	smoothed: 34.1
14:46:03.160 -> heading: 34.5	raw: 3658	a0: 437	windcounts: 38.4	smoothed: 34.5
14:46:03.262 -> heading: 34.9	raw: 3657	a0: 438	windcounts: 38.5	smoothed: 34.9
14:46:03.363 -> heading: 35.2	raw: 3658	a0: 437	windcounts: 38.4	smoothed: 35.2
14:46:03.465 -> heading: 35.6	raw: 3658	a0: 437	windcounts: 38.4	smoothed: 35.6
14:46:03.567 -> heading: 35.8	raw: 3658	a0: 437	windcounts: 38.4	smoothed: 35.8
14:46:03.669 -> heading: 36.1	raw: 3658	a0: 437	windcounts: 38.4	smoothed: 36.1
14:46:03.771 -> heading: 36.3	raw: 3658	a0: 437	windcounts: 38.4	smoothed: 36.3
14:46:03.872 -> heading: 36.5	raw: 3659	a0: 436	windcounts: 38.3	smoothed: 36.5
14:46:03.974 -> heading: 36.7	raw: 3659	a0: 436	windcounts: 38.3	smoothed: 36.7
14:46:04.075 -> heading: 36.9	raw: 3659	a0: 436	windcounts: 38.3	smoothed: 36.9
14:46:04.177 -> heading: 37.0	raw: 3659	a0: 436	windcounts: 38.3	smoothed: 37.0
14:46:04.279 -> heading: 37.1	raw: 3659	a0: 436	windcounts: 38.3	smoothed: 37.1
14:46:04.380 -> heading: 37.3	raw: 3659	a0: 436	windcounts: 38.3	smoothed: 37.3
14:46:04.481 -> heading: 37.4	raw: 3659	a0: 436	windcounts: 38.3	smoothed: 37.4
14:46:04.582 -> heading: 37.5	raw: 3659	a0: 436	windcounts: 38.3	smoothed: 37.5
14:46:04.684 -> heading: 37.6	raw: 3659	a0: 436	windcounts: 38.3	smoothed: 37.6
14:46:04.785 -> heading: 37.6	raw: 3666	a0: 429	windcounts: 37.7	smoothed: 37.6
14:46:04.887 -> heading: 37.4	raw: 3685	a0: 410	windcounts: 36.0	smoothed: 37.4
14:46:04.988 -> heading: 37.1	raw: 3701	a0: 394	windcounts: 34.6	smoothed: 37.1
14:46:05.090 -> heading: 36.9	raw: 3704	a0: 391	windcounts: 34.4	smoothed: 36.9
14:46:05.158 -> heading: 36.6	raw: 3705	a0: 390	windcounts: 34.3	smoothed: 36.6
14:46:05.259 -> heading: 36.4	raw: 3704	a0: 391	windcounts: 34.4	smoothed: 36.4
```

**Comment by RobTillaart** [comment]
Does this output match your expectations?

**Comment by ahmetcemturan** [comment]
Unfortunately not.   İt doesn't seem to work if you look at the numbers.

**Comment by RobTillaart** [comment]
What do you expect to see in the numbers?
Smoothed does follow windcounts but in a tempered way.

You might need to "play" with the ```  heading.setWeight(0.1);``` line e.g. make it 0.5

**Comment by edgar-bonet** [comment]
@ahmetcemturan: You are instantiating a `runningAngle` object in `loop()`, which means that, on each loop iteration you have a brand new instance of this averaging object. This cannot work: the whole idea of averaging relies on something that has some “memory” of the past inputs, in order to average them with the current input. By creating a new `runningAngle` for each data input, you prevent that “memory” to be carried over from a reading to the next. This is why you get no averaging at all: the object has no “past” to average its input with.

You should instead instantiate the object at global scope. If you need to initialize it (e.g. with `setWeight()`), do it once and only once, in `setup()`. Then, in `loop()`, call `add()` for one reading.

**Comment by ahmetcemturan** [comment]
Thank you soo much.  It works and I have already inserted it into the main code.   
One question instead of +-180 degrees I need 0-359 for the weather station.  I implemented it with if...  Result negative, add to 360.  İt works but is there a way in the library for this?  I also think that both of your libraries need to be mentioned in the as5600 git as they are really practical solutions...
Thanks again.

**Comment by ahmetcemturan** [comment]
> 

Thank you too for the explanation.  Very obvious when You read it.

**Comment by RobTillaart** [comment]
> İt works but is there a way in the library for this? 

No, the library has no support for such functionality. 

It would imply to have the following functions added to the library
- **setOffset(float angle = 0)** - note that angle can be interpreted as DEGREES or RADIANS
- **float getOffset()** to see the current offset.

This could be worth the effort (4 bytes RAM ```float _offset;``` , max 10 lines of code).
- it would adjust the range to 0 .. 360 as you needed
- it would allow to adjust between magnetic north and absolute north (when used with compass sensor)
- maybe more

On the other hand it is very easy to add the needed offset code like you did. 
So I won't add offset functions to the library.

**Comment by RobTillaart** [comment]
@ahmetcemturan 
If there are no further questions you may close the issue.

**Comment by RobTillaart** [comment]
@ahmetcemturan 

I had a look at the AS5600 and it looks indeed interesting.
In fact interesting enough to write a library today - https://github.com/RobTillaart/AS5600

I cannot test it as I have no hardware (and only little time coming days).
If you have time to spare would you please give it a try?

**Comment by ahmetcemturan** [comment]
I definitely will try it out.   
Also if You have ordered a sensor make sure it is shipped with its specially polarised magnet..

**Comment by RobTillaart** [comment]
I've not ordered one yet, I asked my favorite shop to get them in their assortiment.
