### ISSUE TITLE
Add runtime angle-type change

### ISSUE THREAD

**Issue by RobTillaart** [RobTillaart/runningAngle#12]
- **setType(const enum AngleType type = DEGREES)**

the current ```_average ``` should be converted depending on "old and new" type.

Assuming GRADIANS are added  #11   (this is done)
- 3 types => 6 conversions....  (or 4 if you use one as intermediate)
- check for no conversion => old == new

Question: is this needed? 
- It adds relative a lot of code to the library while it will be seldom used (assumption)
- The user can easily do his own conversion, with less code.

(low prio)

**Comment by edgar-bonet** [comment]
I have a hard time imagining a situation where you would want to switch units in the middle of a running sketch. Personally I would assume [YAGNI][].

[YAGNI]: https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it

**Comment by RobTillaart** [comment]
Very true, I can't think of one either but it just popped my mind and I would not loose the thought.
I'll close the issue.
