### ISSUE TITLE
Add midPoint(angle)

### ISSUE THREAD

**Issue by RobTillaart** [RobTillaart/runningAngle#16]
Triggered by #15 

The default of the library is to have a midpoint around 0 degrees / radian / gradian.
This is useful in some applications but not in others. 

Two functions could be added to change this midPoint 

- **setMidPoint(float angle)** 
- **getMidPoint()** default returns 180 degrees. 

Need one float to adjust the midpoint.

**Comment by Tobbera** [comment]
I see you are commenting on the performance side of things. How about using degrees*100 int16 throughout the whole code? That is for example float = 250.55 degrees is instead int = 25055.  It can easily be converted to float before and/or after your library if needed. 

![bild](https://user-images.githubusercontent.com/12694196/219412331-6089b872-1a76-4b4e-9dfb-c3a059d74a0b.png)

**Comment by RobTillaart** [comment]
int16_t is an idea I had before however it fails when adding anything above 328 degrees.
Unless you do all the math in -180 - 180 range.
Furthermore one would loose precision although only specific apps would.
Also note that when using radians floats are a natural fit too (range + precision)

Using int32 is slower again but could be an option as it would have a large range, 
- different conversion depending on type!
(I have a library with fast sinus etc based upon integer lookup tables)

My current thought is that allowing any midpoint is overkill.
If I restrict the 0.2.0 to only select between -180..180 or 0..360 then 95% of the applications are happy (assumption)
Having only 2 modi operandi will make math simpler.

I "freeze" this version and refactor it into a 2 modi version and see what performance it brings.

**Comment by Tobbera** [comment]
Thank you for your insights! It was just something that came to my mind while I was coding. I will try your dev-version with 0..360 output tomorrow.

**Comment by RobTillaart** [comment]
@Tobbera 
The twoModi branch is now building too, two functions to select the mode (interval)

(yes the function names should be improved :)

I'll try to do performance tomorrow.

**Comment by RobTillaart** [comment]
Performance did not change in my test.

![image](https://user-images.githubusercontent.com/462844/220583173-1c895369-3338-4d9a-86eb-e94f773a3d2e.png)

After a few days of reflection I think the **setMidPoint()** is overshoot in functionality. 
The two modi solution is much simpler and solves your need and probably many others.
So I will merge the two-modi branch into main.
The midpoint / develop branch will be removed.
