### ISSUE TITLE
Meaning and default value of the weight

### ISSUE THREAD

**Issue by edgar-bonet** [RobTillaart/runningAngle#3]
The meaning of the “weight” parameter is not clear from the documentation and, short of reading the source code, the user has no way of knowing how to set it.
                                                                         
This parameter is variously called “[smoothing factor][wp]” or “[smoothing coefficient][rg]”. It is important to note that, the lower this coefficient, the stronger the smoothing effect. One way to get an intuitive understanding of the coefficient is to compare this filter with a simple moving average. An exponentially weighted moving average of smoothing factor α has roughly the same smoothing performance as a simple moving average of length N provided
                                                                         
α = 2 / (N+1)                                                            
                                                                         
Another way to look at this coefficient is from the perspective of digital low-pass filters. Assuming a constant sampling period ΔT, the time constant of the filter is
                                                                         
τ ≈ ΔT / α                                                               
                                                                         
provided α ≪ 1. The cutoff frequency is then                             
                                                                         
f<sub>c</sub> = 1/(2 π τ)                                                  
                                                                         
Some clues about the meaning of the coefficient should be provided in the documentation.
                                                                         
Also, the default value (namely 0.8) seems odd, as it provides very little smoothing. It is roughly equivalent to a simple moving average of length 1.5 (whatever that may mean). I would suggest setting a much smaller default value. Maybe something like 0.2, which is about the same as averaging 9&nbsp;samples.
                                                                         
[wp]: https://en.wikipedia.org/wiki/Exponential_smoothing                
[rg]: https://www.researchgate.net/publication/313992620_The_Exponentially_Weighted_Moving_Average

**Comment by RobTillaart** [comment]
Feel free to expand the **readme.md** file 

Yes, the default of **0.8** was left from one of my test runs, the effect - high low **α** - should be explained too

In a first concept **weight** was set in the constructor however that does not allow run time adjustment e.g. make the **α** dependent on the angle. 

If you have a better name for **weight** just propose them and keep it in sync with the **readme.md**

**Comment by edgar-bonet** [comment]
I am OK with the name “weight”, as it is the weight of the current sample in the average. I don't get the use case for an angle-dependent **α**, but it sure doesn't hurt to allow this possibility.

I will try to expand the README file in order to provide more complete documentation, but I need some rest before ;-)

**Comment by RobTillaart** [comment]
a side thought:

Should we replace
```_average = wrap(_average + _weight * wrap(angle - _average));```

with
```_average = wrap(_average + _weight * (angle - _average));```

as it is on average faster as there is a chance that  **_weight * (angle - _average)**  
will be under the "wrap threshold" while ** (angle - _average)** is not.

----
update ==> yes, running the timing sketch
 
Average angle: 61.56 deg
Average time: 643.06 CPU cycles   // original

Average angle: 61.56 deg
Average time: 503.09 CPU cycles   // proposed

However I have second thoughts if it is equivalent.

----
update
only equivalent because parameter angle was always within 0..90
